Update GH Action

diff --git a/.github/workflows/check-dockerfile-and-translations.yml b/.github/workflows/check-dockerfile-and-translations.yml
--- a/.github/workflows/check-dockerfile-and-translations.yml
+++ b/.github/workflows/check-dockerfile-and-translations.yml
@@ -201,3 +201,8 @@ jobs:
                 body
               });
             }
+      - name: Fail check if something is wrong
+        if: steps.build-status.outputs.status == 'failure' || steps.compare-translations.outputs.all_translated == 'false'
+        run: |
+          echo "Docker build failed or translations are missing. Failing the check."
+          exit 1
